#[doc = "🙈"]
pub const SEE_NO_EVIL_MONKEY: crate::Emoji = crate::Emoji {
	glyph:                "🙈",
	codepoint:            &[128584u32],
	status:               crate::Status::FullyQualified,
	introduction_version: crate::Version { major: 0u8, minor: 6u8, patch: 0u8 },
	name:                 "see-no-evil monkey",
	group:                crate::Group::SmileysEmotion,
	subgroup:             crate::Subgroup::MonkeyFace,
	is_variant:           false,
	variants:             &[],
	skin_tones:           None,
	gender_variants:      None,
	annotations:          &[
		#[cfg(feature = "bn")]
		crate::Annotation {
			lang:     "bn",
			tts:      Some("কোনো খ\u{9be}র\u{9be}প জিনিস দেখব ন\u{9be}"),
			keywords: &[
				"",
				"অঙ\u{9cd}গভঙ\u{9cd}গি",
				"জীবজন\u{9cd}ত\u{9c1}",
				"দেখতে প\u{9be}রব ন\u{9be}",
				"দেখ\u{9be}",
				"ন\u{9be}",
				"নিষিদ\u{9cd}ধ",
				"ব\u{9be}\u{981}দর",
				"ব\u{9be}নর",
				"ভ\u{9c1}লেই গেছি",
				"ম\u{9c1}খ",
				"হে ঈশ\u{9cd}বর",
			],
		},
		#[cfg(feature = "da")]
		crate::Annotation {
			lang:     "da",
			tts:      Some("ikke se"),
			keywords: &["", "abe", "dyr", "glemt", "hemmelighed", "pinlig", "skjule", "tre vise aber"],
		},
		#[cfg(feature = "de")]
		crate::Annotation {
			lang:     "de",
			tts:      Some("sich die Augen zuhaltendes Affengesicht"),
			keywords: &[
				"",
				"affe",
				"affengesicht",
				"augen",
				"böse",
				"geheimnis",
				"gemein",
				"geste",
				"nein",
				"omg",
				"sehen",
				"tier",
				"verboten",
				"vergessen",
				"verstecken",
				"zuhalten",
			],
		},
		#[cfg(feature = "en")]
		crate::Annotation {
			lang:     "en",
			tts:      Some("see-no-evil monkey"),
			keywords: &[
				"",
				"embarrassed",
				"evil",
				"face",
				"forbidden",
				"forgot",
				"gesture",
				"hide",
				"monkey",
				"no",
				"omg",
				"prohibited",
				"scared",
				"secret",
				"smh",
				"watch",
			],
		},
		#[cfg(feature = "en-gb")]
		crate::Annotation {
			lang:     "en-gb",
			tts:      Some("see-no-evil monkey"),
			keywords: &[
				"",
				"embarrassed",
				"evil",
				"face",
				"forbidden",
				"forgot",
				"gesture",
				"hide",
				"monkey",
				"no",
				"omg",
				"prohibited",
				"scared",
				"secret",
				"smh",
				"watch",
			],
		},
		#[cfg(feature = "es")]
		crate::Annotation {
			lang:     "es",
			tts:      Some("mono con los ojos tapados"),
			keywords: &["", "cara", "mal", "mono", "prohibido"],
		},
		#[cfg(feature = "es-mx")]
		crate::Annotation {
			lang:     "es-mx",
			tts:      Some("mono con los ojos tapados"),
			keywords: &["", "cara", "mono", "no ver"],
		},
		#[cfg(feature = "et")]
		crate::Annotation {
			lang:     "et",
			tts:      Some("kaetud silmadega ahv"),
			keywords: &["", "ahv", "keelatud", "keeld", "kuri", "nägu", "vaatamine"],
		},
		#[cfg(feature = "fi")]
		crate::Annotation {
			lang:     "fi",
			tts:      Some("en näe pahaa"),
			keywords: &["", "apina", "ei", "ele", "kielletty", "paholainen", "pelokas"],
		},
		#[cfg(feature = "fr")]
		crate::Annotation {
			lang:     "fr",
			tts:      Some("singe ne rien voir"),
			keywords: &[
				"",
				"animal",
				"caché",
				"effrayé",
				"embarras",
				"geste",
				"gêne",
				"interdit",
				"ne pas voir",
				"non",
				"omd",
				"oubli",
				"peur",
				"rien vu rien entendu",
				"secret",
				"singe",
				"visage",
				"voir",
				"yeux",
			],
		},
		#[cfg(feature = "hi")]
		crate::Annotation {
			lang:     "hi",
			tts:      Some("ब\u{941}रा मत द\u{947}खो, गा\u{902}धी जी का बन\u{94d}दर"),
			keywords: &[
				"",
				"गा\u{902}धी जी का बन\u{94d}दर",
				"पश\u{941}",
				"ब\u{902}दर",
				"ब\u{941}रा मत द\u{947}खो",
				"ब\u{941}रा मत द\u{947}खो ब\u{902}दर",
			],
		},
		#[cfg(feature = "hu")]
		crate::Annotation {
			lang:     "hu",
			tts:      Some("nem láttam semmit"),
			keywords: &[
				"",
				"bújócska",
				"elbújik",
				"elfelejt",
				"ijedt",
				"majom",
				"nem",
				"nem figyelek",
				"nem lát semmit",
				"tilos",
				"zavarban van",
				"állat",
			],
		},
		#[cfg(feature = "it")]
		crate::Annotation {
			lang:     "it",
			tts:      Some("non vedo"),
			keywords: &[
				"",
				"faccina",
				"faccina della scimmietta",
				"gesto",
				"non guardo",
				"non posso guardare",
				"proibito",
				"scimmia",
				"scimmietta",
				"scimmietta non vedo",
				"segreto",
				"vietato",
			],
		},
		#[cfg(feature = "ja")]
		crate::Annotation {
			lang:     "ja",
			tts:      Some("見ざる"),
			keywords: &["", "三猿", "動物", "猿", "目隠し", "隠す"],
		},
		#[cfg(feature = "ko")]
		crate::Annotation {
			lang:     "ko",
			tts:      Some("눈을 가리고 있는 원숭이"),
			keywords: &[
				"",
				"금지",
				"금지된",
				"나쁜것은 보지도 말라",
				"동물",
				"맙소사",
				"무서운",
				"보다",
				"볼수 없음",
				"부끄러워",
				"비밀",
				"손으로 눈을 가린 원숭이",
				"아니",
				"아무것도 안 보려는 원숭이",
				"악마",
				"얼굴",
				"오마이갓",
				"원숭이",
				"제스처",
			],
		},
		#[cfg(feature = "lt")]
		crate::Annotation {
			lang:     "lt",
			tts:      Some("užsidengusi akis beždžionė"),
			keywords: &[
				"",
				"beždžionė",
				"blogis",
				"draudžiama",
				"gyvūnas",
				"matyti",
				"negaliu žiūrėti",
				"uždrausta",
				"veidas",
			],
		},
		#[cfg(feature = "ms")]
		crate::Annotation {
			lang:     "ms",
			tts:      Some("monyet tutup mata"),
			keywords: &[
				"",
				"bukan",
				"jahat",
				"jangan lihat perkara tak baik",
				"kejahatan",
				"larang",
				"lihat",
				"monyet",
				"muka",
				"tegah",
				"terlarang",
				"tidak",
			],
		},
		#[cfg(feature = "nb")]
		crate::Annotation {
			lang:     "nb",
			tts:      Some("ser ingenting ondt"),
			keywords: &["", "ape", "fjes", "forbudt", "ikke", "ser ikke"],
		},
		#[cfg(feature = "nl")]
		crate::Annotation {
			lang:     "nl",
			tts:      Some("geen kwaad zien"),
			keywords: &[
				"",
				"aap",
				"beschaamd",
				"dier",
				"gebaar",
				"geen",
				"gezicht",
				"kwaad",
				"niet",
				"niet kijken",
				"schaamte",
				"uit den boze",
				"verboden",
				"verlegen",
				"wil niet zien",
				"zie",
				"zien",
			],
		},
		#[cfg(feature = "pl")]
		crate::Annotation {
			lang:     "pl",
			tts:      Some("małpa zasłaniająca oczy"),
			keywords: &[
				"",
				"gest",
				"małpa",
				"małpka",
				"nie",
				"nie widzieć",
				"nie widzę",
				"niedobre",
				"zabronione",
				"zakrywam oczy",
				"zwierzę",
			],
		},
		#[cfg(feature = "pt")]
		crate::Annotation {
			lang:     "pt",
			tts:      Some("macaco que não vê nada"),
			keywords: &[
				"",
				"envergonhado",
				"macaco",
				"não veja o mal",
				"não vi nada",
				"olhos",
				"tapados",
				"vergonha",
			],
		},
		#[cfg(feature = "ru")]
		crate::Annotation {
			lang:     "ru",
			tts:      Some("ничего не вижу"),
			keywords: &["", "глаза", "запрещено", "зрение", "нельзя", "обезьяна"],
		},
		#[cfg(feature = "sv")]
		crate::Annotation {
			lang:     "sv",
			tts:      Some("apa ser inget"),
			keywords: &["", "apa", "håller för", "inget", "ser", "ögon"],
		},
		#[cfg(feature = "th")]
		crate::Annotation {
			lang:     "th",
			tts:      Some("ล\u{e34}งป\u{e34}ดตา"),
			keywords: &["", "ป\u{e34}ดตา", "ล\u{e34}ง"],
		},
		#[cfg(feature = "uk")]
		crate::Annotation {
			lang:     "uk",
			tts:      Some("мавпа, що не бачить"),
			keywords: &[
				"",
				"бачити",
				"заборонено",
				"зло",
				"мавпа",
				"не бачу",
				"не бачу зла",
				"обличчя",
				"що не бачить",
				"що не бачить зла",
			],
		},
		#[cfg(feature = "vi")]
		crate::Annotation {
			lang:     "vi",
			tts:      Some("khỉ không nhìn điều xấu"),
			keywords: &["", "cấm", "khỉ", "mặt", "nhìn", "điều xấu"],
		},
		#[cfg(feature = "zh")]
		crate::Annotation {
			lang:     "zh",
			tts:      Some("非礼勿视"),
			keywords: &["", "不许看", "别看", "尴尬", "糗", "脸", "蒙住眼睛", "蒙眼"],
		},
		#[cfg(feature = "zh-hant")]
		crate::Annotation {
			lang:     "zh-hant",
			tts:      Some("非禮勿視"),
			keywords: &["", "不看", "動物", "我的天", "遮眼"],
		},
	],
};
#[doc = "🙊"]
pub const SPEAK_NO_EVIL_MONKEY: crate::Emoji = crate::Emoji {
	glyph:                "🙊",
	codepoint:            &[128586u32],
	status:               crate::Status::FullyQualified,
	introduction_version: crate::Version { major: 0u8, minor: 6u8, patch: 0u8 },
	name:                 "speak-no-evil monkey",
	group:                crate::Group::SmileysEmotion,
	subgroup:             crate::Subgroup::MonkeyFace,
	is_variant:           false,
	variants:             &[],
	skin_tones:           None,
	gender_variants:      None,
	annotations:          &[
		#[cfg(feature = "bn")]
		crate::Annotation {
			lang:     "bn",
			tts:      Some("কোনো খ\u{9be}র\u{9be}প কথ\u{9be} বলব ন\u{9be}"),
			keywords: &[
				"",
				"অঙ\u{9cd}গভঙ\u{9cd}গি",
				"খ\u{9be}র\u{9be}প কথ\u{9be} বলব ন\u{9be}",
				"দ\u{9c1}ষ\u{9cd}ট",
				"ন\u{9be}",
				"নিষিদ\u{9cd}ধ",
				"প\u{9cd}র\u{9be}ণী",
				"ব\u{9be}\u{981}দর",
				"ব\u{9be}নর",
				"বোব\u{9be}র শত\u{9cd}র\u{9c1} নেই",
				"ম\u{9c1}খ",
			],
		},
		#[cfg(feature = "da")]
		crate::Annotation {
			lang:     "da",
			tts:      Some("ikke tale"),
			keywords: &["", "abe", "dyr", "hemmelighed", "tre vise aber"],
		},
		#[cfg(feature = "de")]
		crate::Annotation {
			lang:     "de",
			tts:      Some("sich den Mund zuhaltendes Affengesicht"),
			keywords: &[
				"",
				"affe",
				"affengesicht",
				"böse",
				"geheimnis",
				"gemein",
				"geste",
				"hand",
				"heimlich",
				"leise",
				"mund",
				"nein",
				"sagen",
				"sprechen",
				"still",
				"tier",
				"ups",
				"verboten",
				"zuhalten",
			],
		},
		#[cfg(feature = "en")]
		crate::Annotation {
			lang:     "en",
			tts:      Some("speak-no-evil monkey"),
			keywords: &[
				"",
				"animal",
				"evil",
				"face",
				"forbidden",
				"gesture",
				"monkey",
				"no",
				"not",
				"oops",
				"prohibited",
				"quiet",
				"secret",
				"speak",
				"stealth",
			],
		},
		#[cfg(feature = "en-gb")]
		crate::Annotation {
			lang:     "en-gb",
			tts:      Some("speak-no-evil monkey"),
			keywords: &[
				"",
				"animal",
				"evil",
				"face",
				"forbidden",
				"gesture",
				"monkey",
				"no",
				"not",
				"oops",
				"prohibited",
				"quiet",
				"secret",
				"speak",
				"stealth",
			],
		},
		#[cfg(feature = "es")]
		crate::Annotation {
			lang:     "es",
			tts:      Some("mono con la boca tapada"),
			keywords: &["", "cara", "mal", "mono", "prohibido"],
		},
		#[cfg(feature = "es-mx")]
		crate::Annotation {
			lang:     "es-mx",
			tts:      Some("mono con la boca tapada"),
			keywords: &["", "cara", "mono", "no hablar"],
		},
		#[cfg(feature = "et")]
		crate::Annotation {
			lang:     "et",
			tts:      Some("kaetud suuga ahv"),
			keywords: &["", "ahv", "keelatud", "keeld", "kuri", "nägu", "rääkimine"],
		},
		#[cfg(feature = "fi")]
		crate::Annotation {
			lang:     "fi",
			tts:      Some("en puhu pahaa"),
			keywords: &["", "apina", "eläin", "hiljaa", "hups", "kielletty"],
		},
		#[cfg(feature = "fr")]
		crate::Annotation {
			lang:     "fr",
			tts:      Some("singe ne rien dire"),
			keywords: &[
				"",
				"animal",
				"bouche cousue",
				"chut",
				"geste",
				"interdit",
				"motus",
				"muet",
				"non",
				"parler",
				"se taire",
				"secret",
				"silence",
				"singe",
				"visage",
			],
		},
		#[cfg(feature = "hi")]
		crate::Annotation {
			lang:     "hi",
			tts:      Some("ब\u{941}रा मत बोलो, गा\u{902}धी जी का बन\u{94d}दर"),
			keywords: &[
				"",
				"गा\u{902}धी जी का बन\u{94d}दर",
				"पश\u{941}",
				"ब\u{902}दर",
				"ब\u{941}रा मत बोलो",
				"ब\u{941}रा मत बोलो ब\u{902}दर",
			],
		},
		#[cfg(feature = "hu")]
		crate::Annotation {
			lang:     "hu",
			tts:      Some("nem szólok semmit"),
			keywords: &[
				"",
				"bocsánat",
				"elnézést",
				"elszóltam magam",
				"hoppá",
				"majom",
				"nem",
				"nem beszél",
				"nem szól semmit",
				"tilos",
				"titok",
				"állat",
			],
		},
		#[cfg(feature = "it")]
		crate::Annotation {
			lang:     "it",
			tts:      Some("non parlo"),
			keywords: &[
				"",
				"animale",
				"animali",
				"faccina",
				"in silenzio",
				"monello",
				"proibito",
				"scimmia",
				"scimmietta non parlo",
				"segreto",
				"vietato",
			],
		},
		#[cfg(feature = "ja")]
		crate::Annotation {
			lang:     "ja",
			tts:      Some("言わざる"),
			keywords: &["", "三猿", "内緒", "猿", "秘密", "黙る"],
		},
		#[cfg(feature = "ko")]
		crate::Annotation {
			lang:     "ko",
			tts:      Some("입을 막고 있는 원숭이"),
			keywords: &[
				"",
				"금지",
				"나쁜것은 말하지도 말라",
				"말하다",
				"비밀",
				"손으로 입을 가린 원숭이",
				"악마",
				"얼굴",
				"웁스",
				"원숭이",
				"제스처",
				"조용한",
			],
		},
		#[cfg(feature = "lt")]
		crate::Annotation {
			lang:     "lt",
			tts:      Some("užsidengusi burną beždžionė"),
			keywords: &["", "beždžionė", "blogis", "gyvūnas", "nekalbu", "uždrausta", "veidas"],
		},
		#[cfg(feature = "ms")]
		crate::Annotation {
			lang:     "ms",
			tts:      Some("monyet tutup mulut"),
			keywords: &[
				"",
				"bukan",
				"jahat",
				"jangan sebut perkara tak baik",
				"larang",
				"monyet",
				"muka",
				"sebut",
				"tegah",
				"terlarang",
				"tidak",
				"tidak bercakap yang jahat",
			],
		},
		#[cfg(feature = "nb")]
		crate::Annotation {
			lang:     "nb",
			tts:      Some("sier ingenting ondt"),
			keywords: &["", "ape", "fjes", "forbudt", "holder munn", "ikke", "sier ikke"],
		},
		#[cfg(feature = "nl")]
		crate::Annotation {
			lang:     "nl",
			tts:      Some("geen kwaad spreken"),
			keywords: &[
				"",
				"aap",
				"gebaar",
				"geen",
				"geheim",
				"gezicht",
				"kwaad",
				"niet",
				"oeps",
				"spreken",
				"stiekem",
				"uit den boze",
				"verboden",
			],
		},
		#[cfg(feature = "pl")]
		crate::Annotation {
			lang:     "pl",
			tts:      Some("małpa zasłaniająca pyszczek"),
			keywords: &[
				"",
				"buźka",
				"co ja mówię",
				"gest",
				"głowa",
				"małpa",
				"małpka",
				"nie",
				"nie mówić",
				"nie mówię",
				"niedobre",
				"zabronione",
				"zakrywam usta",
				"zwierzę",
			],
		},
		#[cfg(feature = "pt")]
		crate::Annotation {
			lang:     "pt",
			tts:      Some("macaco que não fala nada"),
			keywords: &[
				"",
				"animal",
				"boca tapada",
				"macaco",
				"não",
				"não fale nada",
				"não posso contar",
				"não posso falar",
				"segredo",
				"silencio",
				"ups",
			],
		},
		#[cfg(feature = "ru")]
		crate::Annotation {
			lang:     "ru",
			tts:      Some("ничего никому не скажу"),
			keywords: &["", "закрыт", "запрещено", "лапы", "молчание", "обезьяна", "рот"],
		},
		#[cfg(feature = "sv")]
		crate::Annotation {
			lang:     "sv",
			tts:      Some("apa säger inget"),
			keywords: &["", "apa", "hemlighet", "håller för", "inget", "munnen", "säger", "tyst"],
		},
		#[cfg(feature = "th")]
		crate::Annotation {
			lang:     "th",
			tts:      Some("ล\u{e34}งป\u{e34}ดปาก"),
			keywords: &["", "ป\u{e34}ดปาก", "ล\u{e34}ง"],
		},
		#[cfg(feature = "uk")]
		crate::Annotation {
			lang:     "uk",
			tts:      Some("мавпа, що не говорить"),
			keywords: &[
				"",
				"говорити",
				"заборонено",
				"зло",
				"мавпа",
				"мовчу",
				"не говорю лихого",
				"не скажу",
				"обличчя",
				"ой",
				"секрет",
				"що не висловлює зла",
				"що не говорить",
			],
		},
		#[cfg(feature = "vi")]
		crate::Annotation {
			lang:     "vi",
			tts:      Some("khỉ không nói điều xấu"),
			keywords: &["", "cấm", "khỉ", "mặt", "nói", "điều xấu"],
		},
		#[cfg(feature = "zh")]
		crate::Annotation {
			lang:     "zh",
			tts:      Some("非礼勿言"),
			keywords: &["", "不许说", "捂上嘴巴", "捂嘴", "秘密", "脸"],
		},
		#[cfg(feature = "zh-hant")]
		crate::Annotation {
			lang:     "zh-hant",
			tts:      Some("非禮勿言"),
			keywords: &["", "動物", "摀嘴", "禁言"],
		},
	],
};
#[doc = "🙉"]
pub const HEAR_NO_EVIL_MONKEY: crate::Emoji = crate::Emoji {
	glyph:                "🙉",
	codepoint:            &[128585u32],
	status:               crate::Status::FullyQualified,
	introduction_version: crate::Version { major: 0u8, minor: 6u8, patch: 0u8 },
	name:                 "hear-no-evil monkey",
	group:                crate::Group::SmileysEmotion,
	subgroup:             crate::Subgroup::MonkeyFace,
	is_variant:           false,
	variants:             &[],
	skin_tones:           None,
	gender_variants:      None,
	annotations:          &[
		#[cfg(feature = "bn")]
		crate::Annotation {
			lang:     "bn",
			tts:      Some("কোনো খ\u{9be}র\u{9be}প কিছ\u{9c1} শ\u{9c1}নব ন\u{9be}"),
			keywords: &[
				"",
				"অঙ\u{9cd}গভঙ\u{9cd}গি",
				"দ\u{9c1}ষ\u{9cd}ট",
				"নিষিদ\u{9cd}ধ",
				"পশ\u{9c1}প\u{9be}খি",
				"ব\u{9be}\u{981}দর",
				"ম\u{9c1}খ",
				"শোন\u{9be}",
			],
		},
		#[cfg(feature = "da")]
		crate::Annotation {
			lang:     "da",
			tts:      Some("ikke høre"),
			keywords: &["", "abe", "dyr", "hemmelighed", "lytter ikke", "tre vise aber"],
		},
		#[cfg(feature = "de")]
		crate::Annotation {
			lang:     "de",
			tts:      Some("sich die Ohren zuhaltendes Affengesicht"),
			keywords: &[
				"",
				"affe",
				"affengesicht",
				"böse",
				"geheimnis",
				"gemein",
				"geste",
				"hören",
				"nein",
				"ohren",
				"tier",
				"verboten",
				"zuhalten",
				"zuhören",
			],
		},
		#[cfg(feature = "en")]
		crate::Annotation {
			lang:     "en",
			tts:      Some("hear-no-evil monkey"),
			keywords: &[
				"",
				"animal",
				"ears",
				"evil",
				"face",
				"forbidden",
				"gesture",
				"hear",
				"listen",
				"monkey",
				"no",
				"not",
				"prohibited",
				"secret",
				"shh",
				"tmi",
			],
		},
		#[cfg(feature = "en-gb")]
		crate::Annotation {
			lang:     "en-gb",
			tts:      Some("hear-no-evil monkey"),
			keywords: &[
				"",
				"animal",
				"ears",
				"evil",
				"face",
				"forbidden",
				"gesture",
				"hear",
				"listen",
				"monkey",
				"no",
				"not",
				"prohibited",
				"secret",
				"shh",
				"tmi",
			],
		},
		#[cfg(feature = "es")]
		crate::Annotation {
			lang:     "es",
			tts:      Some("mono con los oídos tapados"),
			keywords: &["", "cara", "mal", "mono", "prohibido"],
		},
		#[cfg(feature = "es-mx")]
		crate::Annotation {
			lang:     "es-mx",
			tts:      Some("mono con los oídos tapados"),
			keywords: &["", "cara", "mono", "no oír"],
		},
		#[cfg(feature = "et")]
		crate::Annotation {
			lang:     "et",
			tts:      Some("kaetud kõrvadega ahv"),
			keywords: &["", "ahv", "keelatud", "keeld", "kuri", "kuulamine", "nägu"],
		},
		#[cfg(feature = "fi")]
		crate::Annotation {
			lang:     "fi",
			tts:      Some("en kuule pahaa"),
			keywords: &["", "apina", "ei", "ele", "kielletty"],
		},
		#[cfg(feature = "fr")]
		crate::Annotation {
			lang:     "fr",
			tts:      Some("singe ne rien entendre"),
			keywords: &[
				"",
				"animal",
				"geste",
				"interdit",
				"ne pas entendre",
				"non",
				"oreilles",
				"rien vu rien entendu",
				"secret",
				"singe",
				"sourd",
				"visage",
				"écouter",
			],
		},
		#[cfg(feature = "hi")]
		crate::Annotation {
			lang:     "hi",
			tts:      Some("ब\u{941}रा मत स\u{941}नो, गा\u{902}धी जी का बन\u{94d}दर"),
			keywords: &[
				"",
				"गा\u{902}धी जी का बन\u{94d}दर",
				"पश\u{941}",
				"ब\u{902}दर",
				"ब\u{941}रा मत स\u{941}नो",
				"ब\u{941}रा मत स\u{941}नो ब\u{902}दर",
			],
		},
		#[cfg(feature = "hu")]
		crate::Annotation {
			lang:     "hu",
			tts:      Some("nem hallottam semmit"),
			keywords: &[
				"",
				"fül",
				"hall",
				"majom",
				"nem",
				"nem figyel",
				"nem hall semmit",
				"tilos",
				"titok",
				"állat",
			],
		},
		#[cfg(feature = "it")]
		crate::Annotation {
			lang:     "it",
			tts:      Some("non sento"),
			keywords: &[
				"",
				"animale",
				"animali",
				"faccina",
				"non sentire",
				"orecchie da mercante",
				"scimmia",
				"scimmietta",
				"scimmietta non sento",
				"segreto",
				"vietato",
			],
		},
		#[cfg(feature = "ja")]
		crate::Annotation {
			lang:     "ja",
			tts:      Some("聞かざる"),
			keywords: &["", "三猿", "猿", "秘密"],
		},
		#[cfg(feature = "ko")]
		crate::Annotation {
			lang:     "ko",
			tts:      Some("귀를 막고 있는 원숭이"),
			keywords: &[
				"",
				"금지",
				"나쁜것은 듣지도 말라",
				"동물",
				"듣기",
				"비밀",
				"손으로 귀를 가린 원숭이",
				"쉿",
				"악마",
				"원숭이",
				"제스처",
			],
		},
		#[cfg(feature = "lt")]
		crate::Annotation {
			lang:     "lt",
			tts:      Some("užsidengusi ausis beždžionė"),
			keywords: &[
				"",
				"beždžionė",
				"blogis",
				"draudžiama",
				"gyvūnas",
				"klausyti",
				"neklausau",
				"paslaptis",
				"uždrausta",
				"veidas",
			],
		},
		#[cfg(feature = "ms")]
		crate::Annotation {
			lang:     "ms",
			tts:      Some("monyet tutup telinga"),
			keywords: &[
				"",
				"dengar",
				"dilarang",
				"gerak isyarat",
				"haiwan",
				"jahat",
				"monyet",
				"muka",
				"rahsia",
				"telinga",
				"tidak",
			],
		},
		#[cfg(feature = "nb")]
		crate::Annotation {
			lang:     "nb",
			tts:      Some("hører ingenting ondt"),
			keywords: &["", "ape", "fjes", "forbudt", "hører ikke", "ikke"],
		},
		#[cfg(feature = "nl")]
		crate::Annotation {
			lang:     "nl",
			tts:      Some("geen kwaad horen"),
			keywords: &[
				"",
				"aap",
				"dier",
				"gebaar",
				"geen",
				"geheim",
				"gezicht",
				"horen",
				"kwaad",
				"luisteren",
				"niet",
				"uit den boze",
				"verboden",
				"wil niet horen",
			],
		},
		#[cfg(feature = "pl")]
		crate::Annotation {
			lang:     "pl",
			tts:      Some("małpa zasłaniająca uszy"),
			keywords: &[
				"",
				"buźka",
				"gest",
				"głowa",
				"głuchy",
				"małpa",
				"małpka",
				"nie",
				"nie słyszeć",
				"nie słyszę",
				"niedobre",
				"zabronione",
				"zakrywam uszy",
				"zwierzę",
			],
		},
		#[cfg(feature = "pt")]
		crate::Annotation {
			lang:     "pt",
			tts:      Some("macaco que não ouve nada"),
			keywords: &[
				"",
				"macaco",
				"não ouve nada",
				"não ouça o mal",
				"não ouço",
				"não quero ouvir",
				"ouvidos",
				"tapados",
			],
		},
		#[cfg(feature = "ru")]
		crate::Annotation {
			lang:     "ru",
			tts:      Some("ничего не слышу"),
			keywords: &["", "запрещено", "лапы", "нельзя", "обезьяна", "слух", "уши"],
		},
		#[cfg(feature = "sv")]
		crate::Annotation {
			lang:     "sv",
			tts:      Some("apa hör inget"),
			keywords: &["", "apa", "håller för", "hör", "inget", "öron"],
		},
		#[cfg(feature = "th")]
		crate::Annotation {
			lang:     "th",
			tts:      Some("ล\u{e34}งป\u{e34}ดห\u{e39}"),
			keywords: &["", "ป\u{e34}ดห\u{e39}", "ล\u{e34}ง"],
		},
		#[cfg(feature = "uk")]
		crate::Annotation {
			lang:     "uk",
			tts:      Some("мавпа, що не чує"),
			keywords: &[
				"",
				"заборонено",
				"зло",
				"мавпа",
				"не чую",
				"не чую зла",
				"обличчя",
				"чути",
				"що не чує",
				"що не чує зла",
			],
		},
		#[cfg(feature = "vi")]
		crate::Annotation {
			lang:     "vi",
			tts:      Some("khỉ không nghe điều xấu"),
			keywords: &["", "cấm", "khỉ", "mặt", "nghe", "điều xấu"],
		},
		#[cfg(feature = "zh")]
		crate::Annotation {
			lang:     "zh",
			tts:      Some("非礼勿听"),
			keywords: &["", "嘘", "堵上耳朵", "堵耳", "猴子", "脸"],
		},
		#[cfg(feature = "zh-hant")]
		crate::Annotation {
			lang:     "zh-hant",
			tts:      Some("非禮勿聽"),
			keywords: &["", "不聽", "不許聽", "秘密", "遮耳"],
		},
	],
};
